class Pattern:
    """
    Represents a single piece of art generated by a neural network.
    """

    def __init__(self, neural_network, metadata=None):
        """
        Initializes a pattern with a neural network and optional metadata.

        Args:
            neural_network (NeuralNetwork): The neural network generating the art.
            metadata (dict): Additional information like parents or generation history.
        """
        self.neural_network = neural_network
        self.canvas = None  # Will be generated by the neural network
        self.fitness = 0  # Default fitness score
        self.metadata = metadata if metadata else {}

    def generate_pattern(self):
        """
        Generates the artwork using the neural network.

        Returns:
            None
        """
        self.canvas = self.neural_network.forward(input_data=None)  # Replace with actual input logic

    def evaluate_fitness(self, fitness_evaluator):
        """
        Evaluates the fitness of the pattern using a FitnessEvaluator.

        Args:
            fitness_evaluator (FitnessEvaluator): The fitness evaluation object.

        Returns:
            None
        """
        self.fitness = fitness_evaluator.evaluate_objective(self)

    def mutate(self, mutation_rate):
        """
        Mutates the underlying neural network to introduce variation.

        Args:
            mutation_rate (float): The rate of mutation.

        Returns:
            None
        """
        self.neural_network.mutate(mutation_rate)

    def __repr__(self):
        """
        Provides a string representation of the pattern.

        Returns:
            str: Description of the pattern.
        """
        return f"Pattern(Fitness: {self.fitness}, Metadata: {self.metadata})"
